name: Unexpected Outbound Calls
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  unexpected-outbound-calls:
    name: UnexpectedOutboundCalls
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - run: "curl https://attacker.com -L  || true"
      - run: "curl https://google.com -L  || true"
      - run: "curl microsoft.com:443  --connect-timeout 5 || true"
      - run: "curl amazon.com:443  --connect-timeout 5 || true"
